#ifndef LEPTON_BOARD_CONFIG_H
#define LEPTON_BOARD_CONFIG_H

#include "hardware/i2c.h"
#include "hardware/spi.h"
#include "hardware/uart.h"

#define FPGA_SPI_INSTANCE spi0
#define FPGA_SPI_BAUD_HZ 8000000u
#define FPGA_PIN_MOSI 3
#define FPGA_PIN_SCK 2
#define FPGA_PIN_CS_N 1
#define FPGA_PIN_CRESET_N 4
#define FPGA_PIN_CDONE 5
#define FPGA_PIN_STATUS 6
#define FPGA_PIN_OSC_EN 19
#define FPGA_OSC_STARTUP_MS 1
#define FPGA_RESET_LOW_MS 2
#define FPGA_RESET_RELEASE_MS 5
#define FPGA_DONE_TIMEOUT_MS 500
#define FPGA_EXTRA_CLOCK_BYTES 32

#define FPGA_UART_INSTANCE uart0
#define FPGA_UART_BAUD_HZ 8333333u
#define FPGA_UART_PIN_TX 2
#define FPGA_UART_PIN_RX 3
#define FPGA_UART_RX_RING_BITS 14u
#define FPGA_UART_RX_RING_SIZE (1u << FPGA_UART_RX_RING_BITS)

#define LEPTON_I2C_INSTANCE i2c1
#define LEPTON_I2C_BAUD_HZ 100000u
#define LEPTON_I2C_ADDRESS 0x2au
#define LEPTON_PIN_SDA 22
#define LEPTON_PIN_SCL 23
#define LEPTON_STARTUP_DELAY_MS 5000u

#define LEPTON_WIDTH 160u
#define LEPTON_HEIGHT 120u
#define LEPTON_SEGMENT_BYTES 9600u
#define FPGA_STREAM_SEGMENT_BYTES 7200u
#define LEPTON_FRAME_BYTES (LEPTON_WIDTH * LEPTON_HEIGHT * 2u)

#endif
